"""Immutable analysis settings and target-local TOML loading."""

import tomllib
from collections.abc import Mapping
from pathlib import Path
from typing import Annotated, Self

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    field_serializer,
    model_validator,
)

_Text = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]
_PositiveInt = Annotated[int, Field(gt=0, strict=True)]


class AnalysisConfig(BaseModel):
    """Resolved settings shared by all sources in one analysis."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    languages: frozenset[_Text] = Field(
        default_factory=frozenset, exclude_if=lambda value: not value
    )
    production_patterns: tuple[_Text, ...] = ("**/*.py",)
    test_patterns: tuple[_Text, ...] = ("tests/**/*.py", "**/test_*.py", "**/*_test.py")
    exclusions: tuple[_Text, ...] = (
        ".git/**",
        ".venv/**",
        "venv/**",
        "**/__pycache__/**",
        "build/**",
        "dist/**",
    )
    generated_markers: tuple[_Text, ...] = ("@generated", "Generated by")
    enabled_rules: frozenset[_Text] = frozenset()
    disabled_rules: frozenset[_Text] = frozenset()
    clone_min_statements: _PositiveInt = 2
    clone_min_sloc: _PositiveInt = 6
    complexity_threshold: _PositiveInt = 10
    calibration_profile: _Text = "py-2026.3"
    default_hotspot_count: _PositiveInt = 5
    strict: Annotated[bool, Field(strict=True)] = False

    @model_validator(mode="after")
    def validate_rule_selection(self) -> Self:
        conflicts = self.enabled_rules & self.disabled_rules
        if conflicts:
            raise ValueError(
                f"rules cannot be both enabled and disabled: {', '.join(sorted(conflicts))}"
            )
        return self

    @field_serializer("enabled_rules", "disabled_rules", "languages", when_used="json")
    def serialize_rules(self, values: frozenset[str]) -> list[str]:
        return sorted(values)


def _read_toml(path: Path) -> dict[str, object]:
    try:
        with path.open("rb") as stream:
            return tomllib.load(stream)
    except FileNotFoundError:
        return {}


def _table(value: object, name: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise ValueError(f"{name} must be a TOML table")
    return value


def load_analysis_config(
    target_root: Path,
    *,
    cli_overrides: Mapping[str, object] | None = None,
) -> AnalysisConfig:
    """Merge defaults, pyproject, slop.toml, then explicit CLI settings."""
    project = _read_toml(target_root / "pyproject.toml")
    tool = _table(project.get("tool", {}), "tool")
    settings = dict(_table(tool.get("slop", {}), "tool.slop"))
    settings.update(_read_toml(target_root / "slop.toml"))
    if cli_overrides is not None:
        settings.update(cli_overrides)
    return AnalysisConfig.model_validate(settings)
