"""Behavioral tests for immutable analysis configuration and local loading."""

from pathlib import Path
from tomllib import TOMLDecodeError

import pytest
from pydantic import ValidationError

from slop_measure.config import AnalysisConfig, load_analysis_config


def test_analysis_config_has_conservative_python_defaults() -> None:
    config = AnalysisConfig()

    assert config.production_patterns == ("**/*.py",)
    assert config.test_patterns == (
        "tests/**/*.py",
        "**/test_*.py",
        "**/*_test.py",
    )
    assert config.exclusions == (
        ".git/**",
        ".venv/**",
        "venv/**",
        "**/__pycache__/**",
        "build/**",
        "dist/**",
    )
    assert config.generated_markers == ("@generated", "Generated by")
    assert config.enabled_rules == frozenset()
    assert config.disabled_rules == frozenset()
    assert config.clone_min_statements == 2
    assert config.clone_min_sloc == 6
    assert config.complexity_threshold == 10
    assert config.calibration_profile == "py-2026.3"
    assert config.default_hotspot_count == 5
    assert config.strict is False


def test_analysis_config_normalizes_collection_storage() -> None:
    config = AnalysisConfig.model_validate(
        {
            "production_patterns": ["src/**/*.py"],
            "test_patterns": ["tests/**/*.py"],
            "exclusions": ["vendor/**"],
            "generated_markers": ["generated file"],
            "enabled_rules": ["identity-comprehension", "single-use-temporary"],
            "disabled_rules": ["trivial-wrapper"],
        }
    )

    assert config.production_patterns == ("src/**/*.py",)
    assert config.test_patterns == ("tests/**/*.py",)
    assert config.exclusions == ("vendor/**",)
    assert config.generated_markers == ("generated file",)
    assert config.enabled_rules == frozenset({"identity-comprehension", "single-use-temporary"})
    assert config.disabled_rules == frozenset({"trivial-wrapper"})


def test_analysis_config_is_immutable() -> None:
    config = AnalysisConfig()

    with pytest.raises(ValidationError):
        config.strict = True


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("clone_min_statements", 0),
        ("clone_min_sloc", -1),
        ("complexity_threshold", 0),
        ("default_hotspot_count", -1),
    ],
)
def test_analysis_config_requires_positive_thresholds(field: str, value: int) -> None:
    with pytest.raises(ValidationError):
        AnalysisConfig.model_validate({field: value})


def test_analysis_config_rejects_rules_that_are_both_enabled_and_disabled() -> None:
    with pytest.raises(ValidationError, match="identity-comprehension"):
        AnalysisConfig.model_validate(
            {
                "enabled_rules": {"identity-comprehension"},
                "disabled_rules": {"identity-comprehension"},
            }
        )


def test_analysis_config_rejects_unknown_fields() -> None:
    with pytest.raises(ValidationError):
        AnalysisConfig.model_validate({"unknown_setting": True})


def test_config_json_sorts_rules_and_round_trips_immutable_collections() -> None:
    config = AnalysisConfig.model_validate(
        {
            "enabled_rules": ["single-use-temporary", "identity-comprehension"],
            "disabled_rules": ["trivial-wrapper", "defensive-check"],
            "production_patterns": ["src/**/*.py"],
        }
    )
    payload = config.model_dump(mode="json")

    assert payload["enabled_rules"] == ["identity-comprehension", "single-use-temporary"]
    assert payload["disabled_rules"] == ["defensive-check", "trivial-wrapper"]
    restored = AnalysisConfig.model_validate_json(config.model_dump_json())
    assert restored == config
    assert isinstance(restored.enabled_rules, frozenset)
    assert isinstance(restored.disabled_rules, frozenset)
    assert restored.production_patterns == ("src/**/*.py",)


def test_loader_reads_tool_slop_from_pyproject(tmp_path: Path) -> None:
    (tmp_path / "pyproject.toml").write_text(
        """
[tool.slop]
production_patterns = ["package/**/*.py"]
clone_min_sloc = 9
strict = true
""".strip(),
        encoding="utf-8",
    )

    config = load_analysis_config(tmp_path)

    assert config.production_patterns == ("package/**/*.py",)
    assert config.clone_min_sloc == 9
    assert config.strict is True


def test_loader_reads_top_level_slop_toml(tmp_path: Path) -> None:
    (tmp_path / "slop.toml").write_text(
        """
test_patterns = ["spec/**/*.py"]
complexity_threshold = 12
disabled_rules = ["trivial-wrapper"]
""".strip(),
        encoding="utf-8",
    )

    config = load_analysis_config(tmp_path)

    assert config.test_patterns == ("spec/**/*.py",)
    assert config.complexity_threshold == 12
    assert config.disabled_rules == frozenset({"trivial-wrapper"})


def test_slop_toml_overrides_pyproject_and_keeps_other_file_values(
    tmp_path: Path,
) -> None:
    (tmp_path / "pyproject.toml").write_text(
        """
[tool.slop]
clone_min_sloc = 8
complexity_threshold = 11
""".strip(),
        encoding="utf-8",
    )
    (tmp_path / "slop.toml").write_text(
        """
complexity_threshold = 14
""".strip(),
        encoding="utf-8",
    )

    config = load_analysis_config(tmp_path)

    assert config.clone_min_sloc == 8
    assert config.complexity_threshold == 14


def test_cli_overrides_take_precedence_over_file_values(tmp_path: Path) -> None:
    (tmp_path / "slop.toml").write_text(
        """
complexity_threshold = 12
default_hotspot_count = 7
strict = false
""".strip(),
        encoding="utf-8",
    )

    config = load_analysis_config(
        tmp_path,
        cli_overrides={"complexity_threshold": 15, "strict": True},
    )

    assert config.complexity_threshold == 15
    assert config.default_hotspot_count == 7
    assert config.strict is True


def test_loader_does_not_search_above_the_supplied_target_root(tmp_path: Path) -> None:
    (tmp_path / "pyproject.toml").write_text(
        """
[tool.slop]
complexity_threshold = 99
""".strip(),
        encoding="utf-8",
    )
    target_root = tmp_path / "target"
    target_root.mkdir()

    config = load_analysis_config(target_root)

    assert config.complexity_threshold == 10


def test_loader_rejects_unknown_file_settings(tmp_path: Path) -> None:
    (tmp_path / "slop.toml").write_text(
        "unknown_setting = true",
        encoding="utf-8",
    )

    with pytest.raises(ValidationError):
        load_analysis_config(tmp_path)


@pytest.mark.parametrize("filename", ["slop.toml", "pyproject.toml"])
def test_loader_rejects_invalid_toml(tmp_path: Path, filename: str) -> None:
    (tmp_path / filename).write_text("[unterminated", encoding="utf-8")

    with pytest.raises(TOMLDecodeError):
        load_analysis_config(tmp_path)


@pytest.mark.parametrize("content", ['tool = "invalid"', '[tool]\nslop = "invalid"'])
def test_loader_rejects_non_table_config_sections(tmp_path: Path, content: str) -> None:
    (tmp_path / "pyproject.toml").write_text(content, encoding="utf-8")

    with pytest.raises(ValueError):
        load_analysis_config(tmp_path)


def test_loader_rejects_malformed_config_values(tmp_path: Path) -> None:
    (tmp_path / "slop.toml").write_text('clone_min_sloc = "invalid"', encoding="utf-8")

    with pytest.raises(ValidationError):
        load_analysis_config(tmp_path)
